apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arrgo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sosotechnologies/ecr-build-push-with-version.git
    targetRevision: two-files
    path: build-push-to-ecr
    kustomize:
      namePrefix: build-push-to-ecr-
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true